version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5250:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB:photosGalery
    volumes:
      - photosGalery_pg_data:/bitnami/postgresql
volumes:
  photosGalery_pg_data: